### ISSUE TITLE
Invitation: CiviCRM Release for May 2016

### ISSUE THREAD

**Issue by totten** [civicrm/release-management#1]
Hello. My name is Tim Otten (@totten), and I’m going to be the release-manager for an upcoming iteration of CiviCRM (v4.7.6; scheduled for Wed, May 06, 2016). You’ve submitted a PR to CiviCRM’s master branch which is still open. Thanks for preparing that contribution and having some patience! I want to talk a bit about how we can get it merged for the upcoming release.

For the v4.7.6 release, we’d like to try something a bit different - and we’re looking for some help. There’s currently a backlog of ~70 open PRs[F1] ripe for review. I hope you’ll consider joining a working-group to review a small batch of them.

Most of these PR’s are borderline mergeable -- they pass the automated test-suite and sound plausible on the surface. But they deserve a little more careful peer review.  How does the change look or feel when you actually use it? How good was the test-coverage over that function? What other use-cases might be affected?

I believe that -- if a handful of developers come together and coordinate in QA -- we can make a dent in the backlog. For example, if a couple developers have outstanding fixes for CiviContribute, they can check each others’ work and get both fixes released quicker (and with greater confidence).

If you’d like to participate, please take a look at this planning document:

https://docs.google.com/spreadsheets/d/14j8YgFTeMneuLI7iKOBhZYu1i1oksvKLG47W7hYUwU0/edit?usp=sharing

Skim the working groups to see if one of them appeals to your interests. If you can help with this month’s cycle, add your name and WG preferences under “Contributors”.

If you have comments or issues about process, please feel free to reach out through:
- Developer mailing-list: http://lists.civicrm.org/lists/info/civicrm-dev
- Email (totten at civicrm.org)
- IRC (totten on #civicrm ; generally available during afternoons US/Pacific time)

Thanks!

---

For reference, the following PRs are candidates for this release.
- Group: API Gurus -- Improve the public hooks and APIs used by other developers
  - civicrm/civicrm-core#6612: "Contains' operation for searching multi-select custom fields with the API." submitted by @johanv
  - civicrm/civicrm-core#7047: "Changing something to the domain should leave the domain_version untouched" submitted by @johanv
  - civicrm/civicrm-core#7084: "[Needs review] Structural changes to UFField api and BAO." submitted by @saurabhbatra96
  - civicrm/civicrm-core#7725: "CRM-17867 - Api4 core patches" submitted by @colemanw
  - civicrm/civicrm-core#7847: "CRM-18040 - Remove WP magic quotes during rest requests" submitted by @colemanw
  - civicrm/civicrm-core#7878: "Added an API for Personal Campaign Page" submitted by @digitlimit
  - civicrm/civicrm-core#8027: "CRM-18298 - Implement hook_geocodeFormat" submitted by @PalanteJon
  - civicrm/civicrm-core#8066: "CRM-17570 - CRM_Core_Menu - Fire `alterMenu` hook" submitted by @totten
- Group: Big Schemers -- Improve support for processing data at large-organizations
  - civicrm/civicrm-core#6474: "CRM-17014: REST API does not respect ACLs" submitted by @bhahumanists
  - civicrm/civicrm-core#7103: "CRM-17463 re-work group_contact_cache remove clause to be done on a gâ€¦" submitted by @seamuslee001
  - civicrm/civicrm-core#7902: "CRM-18104 Hook for defining log tables." submitted by @eileenmcnaughton
  - civicrm/civicrm-core#7983: "CRM-17846 - Fixing lock name to be less than 64 characters for MySQL 5.7 compatibility" submitted by @andrewperry
  - civicrm/civicrm-core#7988: "CRM-18193, CRM-18104, CRM-18180 logging definition enhancements"  \* civicrm/civicrm-core#8017: "Fix trigger rebuild for all table columns" submitted by @ejegg
  - civicrm/civicrm-core#8036: "CRM-18212 allow triggers to be managed offline." submitted by @eileenmcnaughton
  - civicrm/civicrm-core#8049: "Revert api - unfortunately this depends of a bunch of pending PRS being merged first" submitted by @eileenmcnaughton
    submitted by @eileenmcnaughton
  - civicrm/civicrm-core#8053: "[Ready for Core Team review] CRM-17463 re-work Group Gontact Cache clause" submitted by @seamuslee001
  - civicrm/civicrm-core#8068: "CRM-17832 - Fix method call to Redis" submitted by @colemanw
- Group: Bill Payers - Improve payment processing  
  - civicrm/civicrm-core#6650: "crm-17125 add contact billing address when no contribution address" submitted by @mallezie
  - civicrm/civicrm-core#6938: "CRM-17123 - Include Transaction ID in membership bulk entry profile" submitted by @joannechester
  - civicrm/civicrm-core#8035: "CRM-18302 - Pass payment processor ID in notify URL" submitted by @mjwright
  - civicrm/civicrm-core#8041: "CRM-18303 - Reload contribution object after update" submitted by @mjwright
  - civicrm/civicrm-core#8047: "CRM-18277 : add test for the contact.source field." submitted by @mlutfy
  - civicrm/civicrm-core#8057: "CRM-18341 Pledges not being completed by completeTransaction" submitted by @eileenmcnaughton
- Group: Blaster Mailings - Improve email composition and delivery
  - civicrm/civicrm-core#6087: "Added call to getRecipients before executing a mail job" submitted by @ShiveringSquirrel
  - civicrm/civicrm-core#7361: "[needs-rebase] Net_SMTP, Auth_SASL, Net_Socket - Load via composer" submitted by @totten
  - civicrm/civicrm-core#7499: "CRM-17754 Include resent headers to ensure that SPF and probably DMARâ€¦" submitted by @seamuslee001
  - civicrm/civicrm-core#7587: "CRM-17629 - JobProcessMailingTest - Test w/mailerBatchLimit & 2x mailings" submitted by @totten
  - civicrm/civicrm-core#7677: "CRM-15202 - allow filtering by group assigned to the mailing." submitted by @jmcclelland
  - civicrm/civicrm-core#7728: "[ready for core team review] CRM-17959 - allow URL to be redirected if the queue ID is invalid butâ€¦" submitted by @andrew-cormick-dockery
  - civicrm/civicrm-core#7815: "CRM-18046 Remove unnecessary permission check on search link in ABtesâ€¦" submitted by @seamuslee001
  - civicrm/civicrm-core#8044: "CRM-18320: Fix URLs with ampersands in CiviMail" submitted by @JKingsnorth
  - civicrm/civicrm-core#8088: "CRM-18345: Don't delete mailing data on email/phone deletion" submitted by @JKingsnorth
  - civicrm/civicrm-drupal#354: "CRM-17667: Drush process mailings" submitted by @JKingsnorth
  - civicrm/civicrm-drupal#362: "CRM-17667
  - civicrm/civicrm-packages#135: "Net_SMTP, Auth_SASL, Net_Socket - Remove. Will use composer." submitted by @totten
- Group: Drupal Way -- Improve integration with Drupal
  - civicrm/civicrm-core#8072: "CRM-17965 - Fix contribution widget on Drupal" submitted by @colemanw
  - civicrm/civicrm-drupal#267: "Adds command to sync users to contacts, useful for thousands of users to..." submitted by @AronNovak
  - civicrm/civicrm-drupal#271: "fix so the correct paths are pulled for this instance site" submitted by @senner
  - civicrm/civicrm-drupal#316: "CRM-16000 Member Role Sync: precedence on role grant/revoke" submitted by @agh1
  - civicrm/civicrm-drupal#321: "CRM-10193 - Allow civicrm-sql-conf and civicrm-sql-cli with empty database" submitted by @mollux
  - civicrm/civicrm-drupal#360: "Updated role sync to support multiple synchronization methods" submitted by @spencerbrooks
- Group: Odd Bunch -- Improve all those other things which fall between the cracks
  - civicrm/civicrm-core#6976: "synchronize php and mysql time zones CRM-15656" submitted by @herbdool
  - civicrm/civicrm-core#7322: "CRM-16395 - Installation with localized default settings" submitted by @samuelsov
  - civicrm/civicrm-core#7813: "CRM-17859 - import contacts from CSV: sanitise / cleanup non-breakingâ€¦" submitted by @saurabhbatra96
  - civicrm/civicrm-core#7877: "CRM-14097 - Scheduled reminders UI problems" submitted by @rajithnishanth82
  - civicrm/civicrm-core#8079: "Crm 18349 4.7" submitted by @sunilpawar
  - civicrm/civicrm-core#8087: "CRM-16617: wrong parameter passing breaks installation" submitted by @jitendrapurohit
  - civicrm/civicrm-core#8089: "--CRM-16617, code fixing for install, changed the parameters of function" submitted by @pradpnayak
- Group: Super Cleaners -- Improve code-quality and style
  - civicrm/civicrm-core#5903: "Adding jasmine testing across domains" submitted by @scardinius
  - civicrm/civicrm-core#7663: "Db dsn" submitted by @julialongtin
  - civicrm/civicrm-core#7823: "Fixes to Group Page PHPUnit test" submitted by @josephlacey
  - civicrm/civicrm-core#8034: "[nfc] CRM-18310 add tests for debug logging and option to specify log formaâ€¦" submitted by @eileenmcnaughton
  - civicrm/civicrm-drupal#340: "mysqli" submitted by @jlillyreed
  - civicrm/civicrm-packages#119: "XML_RPC, PEAR DB Drivers - Remove unused dependencies" submitted by @totten
  - civicrm/civicrm-core#8048: "[NFC] preliminary tidy up for CRM-18332" submitted by @eileenmcnaughton
- Group: Usable Searches -- Improve usability of the major UI's
  - civicrm/civicrm-core#7276: "[unresolved-regression] CRM-17616 - Moving to an arbitrary search page result could lead to incomplete results" submitted by @samuelsov
  - civicrm/civicrm-core#7586: "[ready-for-core-team-review] Add settings to configure recently viewed items stack
  - civicrm/civicrm-core#7825: "Ensure editable buttons don't sit underneath other page elements." submitted by @torrance
  - civicrm/civicrm-core#7833: "Full-text search for Activities in Advanced Search form." submitted by @quoma
  - civicrm/civicrm-core#8045: "CRM-18323- PCP Search implementation like group search" submitted by @Kajakaran
  - civicrm/civicrm-core#8076: "Export relationship custom field CRM-18354" submitted by @sunilpawar
- Group: X Files - Address the creepy and unusual phenomena
  - civicrm/civicrm-core#7990: "CRM-16900. Set secure flag to restrict cookies to SSL where appropriate." submitted by @xurizaemon
  - civicrm/civicrm-core#7991: "CRM-16898. Remove debugging in html5lib." submitted by @xurizaemon

**Comment by totten** [comment]
Just a clarification. The list above is flat, but the planning document (the Google Doc) breaks the items down into groups of 5-10 related PRs (ie proposed working-groups).

I think it's beneficial to form small working-groups of 2-3 people to collaborate on a batch of 5-10 PRs rather than have each person choose PRs a-la-carte. Some reasons/notes:
1. This will be first time for a lot of folks doing code-review on civicrm-core, and there will undoubtedly be questions and judgment-calls in many PRs. If it were me, it would be easier to make those calls if I had a stable partner/buddy and could develop some good rapport/communication (e.g. showing up on IRC/Skype at the same times).
2. I'm expecting we'll have some mix of skills/experience among contributors, and I want to make sure that strengths and weaknesses can be complementary. Administratively (for me as RM), checking that is much harder if we have to do it on PR-by-PR basis; it's easier to check for balance on a group-by-group basis.
3. There's no obligation to accept/reject/review any single PR. Within a WG, you can set priorities however you want.

I'll try to update the listing above to better reflect WGs.

**Comment by digitlimit** [comment]
Hi Totten,
Thanks for this honor. I will be happy to contribute to the upcoming release.
Please advice on further action to take since this its my first time.
Regards 

```
On Wednesday, April 6, 2016 7:28 AM, Tim Otten <notifications@github.com> wrote:
```

 Just a clarification. The list above is flat, but the planning document (the Google Doc) breaks the items down into groups of 5-10 related PRs (ie proposed working-groups).I think it's beneficial to form small working-groups of 2-3 people to collaborate on a batch of 5-10 PRs rather than have each person choose PRs a-la-carte. Some reasons/notes:   
- This will be first time for a lot of folks doing code-review on civicrm-core, and there will undoubtedly be questions and judgment-calls in many PRs. If it were me, it would be easier to make those calls if I had a stable partner/buddy and could develop some good rapport/communication (e.g. showing up on IRC/Skype at the same times).
- I'm expecting we'll have some mix of skills/experience among contributors, and I want to make sure that strengths and weaknesses can be complementary. Administratively (for me as RM), checking that is much harder if we have to do it on PR-by-PR basis; it's easier to check for balance on a group-by-group basis.
- There's no obligation to accept/reject/review any single PR. Within a WG, you can set priorities however you want.
  I'll try to update the listing above to better reflect WGs.—

**Comment by totten** [comment]
@digitlimit , that's great. Please take a minute to look through the WG's and note which one appeals to you. If you're open, then say "Any". Put the choice in the spreadsheet (under "Contributors").

**Comment by eileenmcnaughton** [comment]
I added a sheet in the s/sheet for our WG (Big Schemers) - maybe people will find that useful to look at as a template of sorts for thinkig about Qa
